# This job installs Love.jl and Fluid.jl, and runs tests 
# This occurs when a PR to main is created

name: Tests

permissions:
  actions: write
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
        - master 
        - main
  push:
      branches:
        - master 
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Setup Julia
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'

      # Run tests
      - name: Run test suite
        run: julia --project=. --code-coverage -e 'using Pkg; Pkg.instantiate(); Pkg.test()'

      # Run coverage
      - name: Get coverage
        run: |
          export CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN }}"
          julia --project test/runcoverage.jl
          export total=$(cat coverage.total)
          echo "total=$total" >> $GITHUB_ENV
          cat coverage.md >> "$GITHUB_STEP_SUMMARY"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: FormingWorlds/Obliqua